
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Result<FcmConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConfig(config: FcmConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isAuthenticated() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_authenticated") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getToken() : Promise<Result<OAuthToken | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startOauth() : Promise<Result<AuthResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_oauth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logout() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendFcmMessage(request: SendRequest) : Promise<Result<SendResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_fcm_message", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTemplates() : Promise<Result<TemplateList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTemplate(template: Template) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_template", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTemplate(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_template", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<Result<HistoryList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Android 알림 설정
 */
export type AndroidSettings = { 
/**
 * 우선순위: "high" 또는 "normal"
 */
priority: string; 
/**
 * 알림 채널 ID
 */
channelId: string }
/**
 * APNs (iOS) 알림 설정
 */
export type ApnsSettings = { 
/**
 * 우선순위: "10" (high) 또는 "5" (normal)
 */
priority: string; 
/**
 * 사운드: "default" 또는 커스텀 사운드 파일명
 */
sound?: string | null }
/**
 * OAuth 인증 결과
 */
export type AuthResult = { success: boolean; message: string; token?: OAuthToken | null }
/**
 * FCM 앱 설정
 */
export type FcmConfig = { 
/**
 * Google OAuth 2.0 클라이언트 ID
 */
oauthClientId: string; 
/**
 * OAuth 리다이렉트 URL
 */
oauthRedirectUrl: string; 
/**
 * 외부 토큰 교환 API URL
 */
exchangeCodeUrl: string; 
/**
 * Firebase 프로젝트 ID
 */
firebaseProjectId: string }
/**
 * FCM 메시지 내용
 */
export type FcmMessage = { title: string; body: string }
/**
 * 발송 히스토리 항목
 */
export type HistoryEntry = { id: string; timestamp: string; 
/**
 * "single" or "topic"
 */
messageType: string; title: string; body: string; success: boolean; details: string }
/**
 * 히스토리 목록 (최대 100개)
 */
export type HistoryList = { entries: HistoryEntry[]; maxSize?: number }
/**
 * FCM 메시지 발송 타입
 */
export type MessageType = 
/**
 * 단일 디바이스
 */
"single" | 
/**
 * 토픽
 */
"topic"
/**
 * OAuth 토큰 정보
 */
export type OAuthToken = { accessToken: string; refreshToken?: string; idToken?: string; tokenType: string; expiry: string }
/**
 * FCM 발송 요청
 */
export type SendRequest = { messageType: MessageType; message: FcmMessage; 
/**
 * 단일 디바이스용 토큰
 */
token?: string | null; 
/**
 * 토픽명
 */
topic?: string | null; 
/**
 * Android 설정
 */
android?: AndroidSettings | null; 
/**
 * APNs (iOS) 설정
 */
apns?: ApnsSettings | null }
/**
 * FCM 발송 결과
 */
export type SendResult = { success: boolean; details: string }
/**
 * 메시지 템플릿
 */
export type Template = { id: string; name: string; title: string; body: string; createdAt: string; updatedAt: string }
/**
 * 템플릿 목록
 */
export type TemplateList = { templates: Template[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
